const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const {spawnSync} = require("node:child_process");

const sourcePath = path.join(__dirname, "src", "NamedTransformTest.res");
const originalGeneratedPath = path.join(
  __dirname,
  "src",
  "NamedTransformTest__fixture__Named.res"
);
const renamedGeneratedPath = path.join(
  __dirname,
  "src",
  "NamedTransformTest__fixture__Renamed.res"
);
const originalSource = fs.readFileSync(sourcePath, "utf8");
const originalGenerated = fs.readFileSync(originalGeneratedPath, "utf8");

function sourceHash(source) {
  const input =
    "rescript-embed-lang\0format=1\0config=1\0extension=fixture\0source=" +
    source;
  return crypto.createHash("sha256").update(input, "utf8").digest("hex");
}

function generated(source) {
  return (
    "// @generated by rescript-embed-lang v1\n" +
    "module SourceHash_" +
    sourceHash(source) +
    " = {\n  let default = 42\n}\n"
  );
}

function build() {
  return spawnSync(
    path.join(__dirname, "node_modules", ".bin", "rescript"),
    [],
    {cwd: __dirname, encoding: "utf8"}
  );
}

try {
  let result = build();
  assert.equal(result.status, 0, result.stdout + result.stderr);

  const changedOperation = "query Named { viewer { id name } }";
  fs.writeFileSync(
    sourcePath,
    "module Named = %generated.fixture(\x60" +
      changedOperation +
      "\x60)\n\nlet value = Named.default\n"
  );
  result = build();
  assert.notEqual(result.status, 0, "stale generated source hash should fail compilation");
  assert.match(
    result.stdout + result.stderr,
    /SourceHash_/,
    "stale hash failure should identify the missing source-hash module"
  );

  fs.writeFileSync(originalGeneratedPath, generated(changedOperation));
  result = build();
  assert.equal(result.status, 0, result.stdout + result.stderr);

  const renamedOperation = "query Renamed { viewer { id name } }";
  fs.writeFileSync(
    sourcePath,
    "module Renamed = %generated.fixture(\x60" +
      renamedOperation +
      "\x60)\n\nlet value = Renamed.default\n"
  );
  fs.writeFileSync(renamedGeneratedPath, generated(renamedOperation));
  fs.unlinkSync(originalGeneratedPath);
  result = build();
  assert.equal(result.status, 0, result.stdout + result.stderr);
  assert.equal(fs.existsSync(originalGeneratedPath), false);
} finally {
  fs.writeFileSync(sourcePath, originalSource);
  fs.writeFileSync(originalGeneratedPath, originalGenerated);
  fs.rmSync(renamedGeneratedPath, {force: true});
  build();
}
