module Path = NodeJs.Path
module Process = NodeJs.Process
module Fs = NodeJs.Fs
module CodegenUtils = RescriptEmbedLang__CodegenUtils
module Internal = RescriptEmbedLang__Internal

let colorRed = str => `\x1b[31m${str}\x1b[0m`

module Chokidar = {
  type t
  module Watcher = {
    type t
    @send external onChange: (t, @as(json`"change"`) _, string => promise<unit>) => t = "on"
    @send external onUnlink: (t, @as(json`"unlink"`) _, string => promise<unit>) => t = "on"
    @send external onAdd: (t, @as(json`"add"`) _, string => promise<unit>) => t = "on"
  }
  @module("chokidar") @val external watcher: t = "default"
  @live type watchOptions = {ignored?: array<string>, ignoreInitial?: bool}
  @send external watch: (t, string, ~options: watchOptions=?) => Watcher.t = "watch"
}

module Glob = {
  @live type opts = {dot?: bool, cwd?: string, absolute?: bool}
  @live type glob = {sync: (array<string>, opts) => array<string>}
  @module("fast-glob") external glob: glob = "default"
}

let configVersion = 1
let ownershipHeader = "// @generated by rescript-embed-lang v1"
let toFileBaseName = fileName => Path.basenameExt(fileName, ".res")

module Vm = {
  type context = {regexp: RegExp.t, source: string}
  type options = {timeout: int}

  @module("node:vm") @return(nullable)
  external execRegex: (string, context, options) => option<RegExp.Result.t> = "runInNewContext"
}

@live type extensionPattern = Generic(string) | FirstClass(string)
@live type cardinality = ExactlyOne | First
@live type capture = Numbered(int) | Named(string)
@live
type generatedName =
  | Sequential
  | Regex({pattern: string, flags: string, capture: capture, cardinality: cardinality})

module GeneratedName = {
  @live type extraction = {name: string, matchCount: int}

  @get
  external errorCode: JsExn.t => option<string> = "code"

  @get
  external groups: RegExp.Result.t => option<Dict.t<string>> = "groups"

  let describeCapture = capture =>
    switch capture {
    | Numbered(index) => `numbered capture ${index->Int.toString}`
    | Named(name) => `named capture "${name}"`
    }

  let extractRegex = (~pattern, ~flags, ~capture, ~cardinality, ~source) => {
    let iterationFlags = if (
      cardinality === ExactlyOne && !(flags->String.includes("g")) && !(flags->String.includes("y"))
    ) {
      flags ++ "g"
    } else {
      flags
    }
    let regexp = try {
      RegExp.fromString(pattern, ~flags=iterationFlags)
    } catch {
    | JsExn(error) =>
      panic(
        `invalid ECMAScript regex /${pattern}/${flags}: ${error
          ->JsExn.message
          ->Option.getOr("unknown regex error")}`,
      )
    }
    regexp->RegExp.setLastIndex(0)
    let matches: array<RegExp.Result.t> = []
    let maximumMatches = if cardinality === ExactlyOne {
      2
    } else {
      1
    }
    let stopped = ref(false)

    while !stopped.contents && matches->Array.length < maximumMatches {
      let matched = try {
        Vm.execRegex("regexp.exec(source)", {regexp, source}, {timeout: 100})
      } catch {
      | JsExn(error) =>
        if error->errorCode === Some("ERR_SCRIPT_EXECUTION_TIMEOUT") {
          panic(`generated-name regex /${pattern}/${flags} timed out after 100ms`)
        } else {
          JsExn.throw(error)
        }
      }
      switch matched {
      | None => stopped := true
      | Some(result) =>
        matches->Array.push(result)
        if !(regexp->RegExp.global) && !(regexp->RegExp.sticky) {
          stopped := true
        } else if result->RegExp.Result.fullMatch === "" {
          regexp->RegExp.setLastIndex(regexp->RegExp.lastIndex + 1)
        }
      }
    }

    if matches->Array.length === 0 {
      panic(`generated-name regex /${pattern}/${flags} did not match`)
    }
    if cardinality === ExactlyOne && matches->Array.length > 1 {
      panic(`generated-name regex /${pattern}/${flags} matched more than once`)
    }
    let matched = matches[0]->Option.getOrThrow(~message="expected the first regex match")
    let value = switch capture {
    | Numbered(index) => matched[index]->Option.flatMap(value => value)
    | Named(name) => matched->groups->Option.flatMap(groups => groups->Dict.get(name))
    }
    let captureDescription = capture->describeCapture
    let value = switch value {
    | Some(value) => value
    | None => panic(`${captureDescription} was missing for regex /${pattern}/${flags}`)
    }
    if value === "" {
      panic(`${captureDescription} was empty for regex /${pattern}/${flags}`)
    }
    if !(RegExp.fromString("^[_A-Za-z][_0-9A-Za-z]*$")->RegExp.test(value)) {
      panic(`extracted generated name "${value}" is invalid; expected [_A-Za-z][_0-9A-Za-z]*`)
    }
    {name: value, matchCount: matches->Array.length}
  }

  let extract = (~extension, ~source, config) =>
    switch config {
    | Sequential => None
    | Regex({pattern, flags, capture, cardinality}) =>
      try {
        Some(extractRegex(~pattern, ~flags, ~capture, ~cardinality, ~source).name)
      } catch {
      | JsExn(error) =>
        panic(
          `extension "${extension}": ${error
            ->JsExn.message
            ->Option.getOr("name extraction failed")} (${capture->describeCapture})`,
        )
      }
    }

  let toJson = config =>
    switch config {
    | Sequential => Dict.fromArray([("kind", JSON.Encode.string("sequential"))])->JSON.Encode.object
    | Regex({pattern, flags, capture, cardinality}) =>
      let capture = switch capture {
      | Numbered(index) =>
        Dict.fromArray([
          ("kind", JSON.Encode.string("numbered")),
          ("index", JSON.Encode.int(index)),
        ])->JSON.Encode.object
      | Named(name) =>
        Dict.fromArray([
          ("kind", JSON.Encode.string("named")),
          ("name", JSON.Encode.string(name)),
        ])->JSON.Encode.object
      }
      Dict.fromArray([
        ("kind", JSON.Encode.string("regex")),
        ("pattern", JSON.Encode.string(pattern)),
        ("flags", JSON.Encode.string(flags)),
        ("capture", capture),
        (
          "cardinality",
          JSON.Encode.string(
            switch cardinality {
            | ExactlyOne => "exactlyOne"
            | First => "first"
            },
          ),
        ),
      ])->JSON.Encode.object
    }
}

module FileName = {
  type t = {pattern: extensionPattern}
  let make = (pattern: extensionPattern) => {pattern: pattern}
  let getExtensionName = t =>
    switch t.pattern {
    | Generic(extension) | FirstClass(extension) => extension
    }
  let getFullExtension = t =>
    switch t.pattern {
    | Generic(extension) => `%generated.${extension}`
    | FirstClass(extension) => `%${extension}`
    }
  let toGeneratedFileName = (t, fileName, ~extension="res") =>
    `${toFileBaseName(fileName)}__${t->getExtensionName}.${extension}`
  let toNamedGeneratedFileName = (t, fileName, generatedName, ~extension="res") =>
    `${toFileBaseName(fileName)}__${t->getExtensionName}__${generatedName}.${extension}`
}

module CliArgs = {
  type t = array<string>
  let hasArg = (args, name) => args->Array.includes(name)
  let getArgValue = (args, names) => {
    let index = args->Array.findIndexOpt(item => names->Array.includes(item))
    switch index {
    | Some(index) =>
      switch args[index + 1] {
      | Some(value) if !(value->String.startsWith("--")) => Some(value)
      | _ => None
      }
    | None => None
    }
  }
}

@tag("kind") @live
type generated =
  | WithModuleName({moduleName: string, content: string})
  | NoModuleName({content: string})
@live type emitFileReturn = {path: string, fileName: string}
@live type loc = {line: int, col: int}
@live type fileLocation = {start: loc, end: loc}
@live
type generateConfig<'config> = {
  location: fileLocation,
  path: string,
  config: 'config,
  content: string,
  emitExtraFile: (
    ~extension: string,
    ~content: string,
    ~moduleName: option<string>,
  ) => emitFileReturn,
}
@live
type handleOtherCommandConfig<'config> = {
  command: string,
  args: array<string>,
  config: 'config,
}
@live type setupConfig = {args: CliArgs.t}
@live
type onWatchConfig<'config> = {
  config: 'config,
  runGeneration: (~files: array<string>=?) => promise<unit>,
  debug: string => unit,
}

type t<'config> = {
  fileName: FileName.t,
  generatedName: generatedName,
  setup: setupConfig => promise<'config>,
  generate: generateConfig<'config> => promise<result<generated, string>>,
  cliHelpText: string,
  handleOtherCommand?: handleOtherCommandConfig<'config> => promise<unit>,
  onWatch?: onWatchConfig<'config> => promise<unit>,
}

let defaultSetup = async _ => ()

let make = (
  ~extensionPattern,
  ~generatedName=Sequential,
  ~setup,
  ~generate,
  ~cliHelpText,
  ~handleOtherCommand=?,
  ~onWatch=?,
) => {
  fileName: FileName.make(extensionPattern),
  generatedName,
  setup,
  generate,
  cliHelpText,
  ?handleOtherCommand,
  ?onWatch,
}

let getMatches = (~root) => Glob.glob.sync(["**/*.res"], {cwd: root, absolute: true})
@val external argv: array<option<string>> = "process.argv"

@live
type proposedFile = {
  fileName: string,
  content: string,
  sourcePath: string,
  line: int,
  col: int,
}

let indent = content => content->String.split("\n")->Array.join("\n  ")
let diagnostic = (~path, ~location: fileLocation, ~extension, message) =>
  `${path}:${(location.start.line + 1)->Int.toString}:${(location.start.col + 1)
      ->Int.toString} [${extension}] ${message}`

let proposeForSource = async (t: t<_>, path, ~config, ~outputDir, ~debug) => {
  let extension = FileName.getExtensionName(t.fileName)
  let fullExtension = FileName.getFullExtension(t.fileName)
  let embeds =
    (await path->Internal.findContentInFile([fullExtension]))->Array.filter(embed =>
      "%" ++ embed.extensionName === fullExtension
    )

  switch t.generatedName {
  | Sequential if embeds->Array.length === 0 => []
  | Sequential =>
    let modulesAndExtras = await Promise.all(
      embeds->Array.mapWithIndex(async (embed, index) => {
        let extraFiles: array<proposedFile> = []
        let location = {
          start: {line: embed.loc["start"]["line"], col: embed.loc["start"]["character"]},
          end: {line: embed.loc["end"]["line"], col: embed.loc["end"]["character"]},
        }
        let result = try {
          await t.generate({
            path,
            location,
            config,
            content: embed.contents,
            emitExtraFile: (~extension as extraExtension, ~content, ~moduleName) => {
              debug(`[emit] Emitting extra file with extension .${extraExtension}`)
              let moduleName = moduleName->Option.getOr(`M${(index + 1)->Int.toString}`)
              let fileName = `${toFileBaseName(path)}__${extension}.${moduleName}.${extraExtension}`
              extraFiles->Array.push({
                fileName,
                content,
                sourcePath: path,
                line: location.start.line,
                col: location.start.col,
              })
              {path: Path.resolve([outputDir, fileName]), fileName}
            },
          })
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("generator failed"),
            ),
          )
        }
        switch result {
        | Error(message) => panic(diagnostic(~path, ~location, ~extension, message))
        | Ok(WithModuleName({moduleName, content})) => (moduleName, content, extraFiles)
        | Ok(NoModuleName({content})) => (`M${(index + 1)->Int.toString}`, content, extraFiles)
        }
      }),
    )
    let generatedContent =
      modulesAndExtras
      ->Array.map(((moduleName, content, _)) => `module ${moduleName} = {\n  ${content->indent}\n}`)
      ->Array.join("\n\n")
    let fileName = t.fileName->FileName.toGeneratedFileName(path)
    let generated = {
      fileName,
      content: `${ownershipHeader}\n${generatedContent}`,
      sourcePath: path,
      line: 0,
      col: 0,
    }
    [generated, ...modulesAndExtras->Array.flatMap(((_, _, extras)) => extras)]
  | Regex(_) =>
    let proposed = await Promise.all(
      embeds->Array.map(async embed => {
        let location = {
          start: {line: embed.loc["start"]["line"], col: embed.loc["start"]["character"]},
          end: {line: embed.loc["end"]["line"], col: embed.loc["end"]["character"]},
        }
        let generatedName = try {
          t.generatedName
          ->GeneratedName.extract(~extension, ~source=embed.contents)
          ->Option.getOrThrow
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("name extraction failed"),
            ),
          )
        }
        let extraFiles: array<proposedFile> = []
        let result = try {
          await t.generate({
            path,
            location,
            config,
            content: embed.contents,
            emitExtraFile: (~extension as extraExtension, ~content, ~moduleName) => {
              let artifactName = moduleName->Option.getOr(generatedName)
              let fileName = `${toFileBaseName(
                  path,
                )}__${extension}__${artifactName}.${extraExtension}`
              extraFiles->Array.push({
                fileName,
                content,
                sourcePath: path,
                line: location.start.line,
                col: location.start.col,
              })
              {path: Path.resolve([outputDir, fileName]), fileName}
            },
          })
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("generator failed"),
            ),
          )
        }
        let generatedContent = switch result {
        | Error(message) => panic(diagnostic(~path, ~location, ~extension, message))
        | Ok(WithModuleName({content})) | Ok(NoModuleName({content})) => content
        }
        let fileName = t.fileName->FileName.toNamedGeneratedFileName(path, generatedName)
        [
          {
            fileName,
            content: `${ownershipHeader}\n${generatedContent}\n`,
            sourcePath: path,
            line: location.start.line,
            col: location.start.col,
          },
          ...extraFiles,
        ]
      }),
    )
    proposed->Array.flat
  }
}

@send external caseFold: (string, @as("en-US") _) => string = "toLocaleLowerCase"

let validateCollisions = (files: array<proposedFile>) => {
  let seen: Map.t<string, proposedFile> = Map.make()
  files->Array.forEach(file => {
    let key = file.fileName->caseFold
    switch seen->Map.get(key) {
    | None => seen->Map.set(key, file)
    | Some(previous) =>
      panic(
        `${file.sourcePath}:${(file.line + 1)->Int.toString}:${(file.col + 1)
            ->Int.toString} generated output collision for ${file.fileName
          ->JSON.Encode.string
          ->JSON.stringify}; first proposed at ${previous.sourcePath}:${(previous.line + 1)
            ->Int.toString}:${(previous.col + 1)->Int.toString}`,
      )
    }
  })
}

let validateSourceModuleCollisions = (files: array<proposedFile>, sourceFiles: array<string>) => {
  let userModules = sourceFiles->Array.filterMap(path => {
    let content = try {
      path->Fs.readFileSync->NodeJs.Buffer.toString
    } catch {
    | JsExn(_) => ""
    }
    if content->String.startsWith(ownershipHeader) {
      None
    } else {
      Some((Path.basename(path)->String.toLowerCase, path))
    }
  })

  files->Array.forEach(file => {
    if file.fileName->String.endsWith(".res") {
      let key = file.fileName->String.toLowerCase
      switch userModules->Array.find(((moduleName, _)) => moduleName === key) {
      | None => ()
      | Some((_, userPath)) =>
        panic(
          `${file.sourcePath}:${(file.line + 1)->Int.toString}:${(file.col + 1)
              ->Int.toString} generated module "${file.fileName}" collides with user module "${userPath}"`,
        )
      }
    }
  })
}

module SyncFs = {
  type mkdirOptions = {recursive: bool}
  type rmOptions = {recursive?: bool, force?: bool}

  @module("node:fs") external exists: string => bool = "existsSync"
  @module("node:fs") external readDirectory: string => array<string> = "readdirSync"
  @module("node:fs") external readText: (string, @as("utf8") _) => string = "readFileSync"
  @module("node:fs") external writeText: (string, string) => unit = "writeFileSync"
  @module("node:fs") external makeTemporaryDirectory: string => string = "mkdtempSync"
  @module("node:fs") external makeDirectory: (string, mkdirOptions) => unit = "mkdirSync"
  @module("node:fs") external rename: (string, string) => unit = "renameSync"
  @module("node:fs") external remove: (string, rmOptions) => unit = "rmSync"
  @val external nowMilliseconds: unit => float = "Date.now"
}

let quote = value => value->JSON.Encode.string->JSON.stringify
let makeParentDirectory = path => SyncFs.makeDirectory(Path.dirname(path), {recursive: true})

let prepareConfig = async (~path, ~extension, ~generatedName) => {
  let root = if path->SyncFs.exists {
    try {
      let root =
        path
        ->SyncFs.readText
        ->JSON.parseOrThrow
        ->JSON.Decode.object
        ->Option.getOrThrow(~message="expected a JSON object")
      let version = root->Dict.get("version")->Option.flatMap(JSON.Decode.float)
      if version !== Some(1.0) {
        let version =
          root
          ->Dict.get("version")
          ->Option.map(value => JSON.stringify(value))
          ->Option.getOr("undefined")
        panic(`unsupported existing config version ${version}`)
      }
      root
    } catch {
    | JsExn(error) =>
      panic(
        `cannot update embed-language config ${path->quote}: ${error
          ->JsExn.message
          ->Option.getOr("invalid config")}`,
      )
    }
  } else {
    Dict.fromArray([
      ("version", JSON.Encode.int(configVersion)),
      ("extensions", Dict.make()->JSON.Encode.object),
    ])
  }
  let extensions = switch root->Dict.get("extensions")->Option.flatMap(JSON.Decode.object) {
  | Some(extensions) => extensions
  | None =>
    panic(`cannot update embed-language config ${path->quote}: expected "extensions" object`)
  }
  extensions->Dict.set(
    extension,
    Dict.fromArray([("generatedName", generatedName)])->JSON.Encode.object,
  )
  root->JSON.Encode.object->JSON.stringify(~space=2) ++ "\n"
}

let commitFiles = async (
  ~outputDir,
  ~extension,
  ~files: array<proposedFile>,
  ~configPath,
  ~configContent,
) => {
  let indexPath = Path.join([outputDir, `.rescript-embed-lang-${extension}.json`])
  let previous: array<string> = []
  if indexPath->SyncFs.exists {
    try {
      let root =
        indexPath
        ->SyncFs.readText
        ->JSON.parseOrThrow
        ->JSON.Decode.object
        ->Option.getOrThrow(~message="expected a JSON object")
      let validVersion = root->Dict.get("version")->Option.flatMap(JSON.Decode.float) === Some(1.0)
      let decodedFiles =
        root
        ->Dict.get("files")
        ->Option.flatMap(JSON.Decode.array)
        ->Option.map(values => values->Array.filterMap(JSON.Decode.string))
      switch decodedFiles {
      | Some(ownedFiles) if validVersion =>
        ownedFiles->Array.forEach(file => previous->Array.push(file))
      | _ => ()
      }
    } catch {
    | JsExn(error) =>
      panic(
        `cannot read ownership index ${indexPath->quote}: ${error
          ->JsExn.message
          ->Option.getOr("invalid ownership index")}`,
      )
    }
  }

  let previousSet = previous->Set.fromArray
  let existingByFold: Map.t<string, string> = Map.make()
  outputDir
  ->SyncFs.readDirectory
  ->Array.forEach(fileName => existingByFold->Map.set(fileName->caseFold, fileName))
  files->Array.forEach(file => {
    let existingName = existingByFold->Map.get(file.fileName->caseFold)->Option.getOr(file.fileName)
    let target = Path.join([outputDir, existingName])
    if target->SyncFs.exists && !(previousSet->Set.has(existingName)) {
      let content = target->SyncFs.readText
      if !(content->String.startsWith(ownershipHeader)) {
        panic(
          `${file.sourcePath}:${(file.line + 1)->Int.toString}:${(file.col + 1)
              ->Int.toString} generated file ${file.fileName->quote} collides with user-owned file ${existingName->quote}`,
        )
      }
    }
  })

  let stage = SyncFs.makeTemporaryDirectory(Path.join([outputDir, ".rescript-embed-lang-stage-"]))
  let backup = SyncFs.makeTemporaryDirectory(Path.join([outputDir, ".rescript-embed-lang-backup-"]))
  let transactionId = `${Process.process
    ->Process.pid
    ->Int.toString}-${SyncFs.nowMilliseconds()->Float.toString}`
  let configTemporary = configPath ++ ".tmp-" ++ transactionId
  let configBackup = configPath ++ ".backup-" ++ transactionId
  let affected = Set.fromArray(
    [...previousSet->Set.toArray, ...files->Array.map(file => file.fileName)],
  )

  try {
    files->Array.forEach(file => {
      let staged = Path.join([stage, file.fileName])
      staged->makeParentDirectory
      SyncFs.writeText(staged, file.content)
    })
    let indexJson =
      Dict.fromArray([
        ("version", JSON.Encode.int(configVersion)),
        ("extension", JSON.Encode.string(extension)),
        ("files", files->Array.map(file => file.fileName)->JSON.Encode.stringArray),
      ])->JSON.Encode.object
    SyncFs.writeText(Path.join([stage, "index.json"]), indexJson->JSON.stringify(~space=2) ++ "\n")
    configPath->makeParentDirectory
    SyncFs.writeText(configTemporary, configContent)

    affected->Set.forEach(fileName => {
      let target = Path.join([outputDir, fileName])
      if target->SyncFs.exists {
        let saved = Path.join([backup, fileName])
        saved->makeParentDirectory
        SyncFs.rename(target, saved)
      }
    })
    if indexPath->SyncFs.exists {
      SyncFs.rename(indexPath, Path.join([backup, "index.json"]))
    }
    if configPath->SyncFs.exists {
      SyncFs.rename(configPath, configBackup)
    }

    files->Array.forEach(file => {
      let target = Path.join([outputDir, file.fileName])
      target->makeParentDirectory
      SyncFs.rename(Path.join([stage, file.fileName]), target)
    })
    SyncFs.rename(Path.join([stage, "index.json"]), indexPath)
    SyncFs.rename(configTemporary, configPath)

    SyncFs.remove(configBackup, {force: true})
    SyncFs.remove(backup, {recursive: true, force: true})
    SyncFs.remove(stage, {recursive: true, force: true})
  } catch {
  | JsExn(error) =>
    affected->Set.forEach(fileName => {
      let target = Path.join([outputDir, fileName])
      if target->SyncFs.exists {
        SyncFs.remove(target, {force: true})
      }
      let saved = Path.join([backup, fileName])
      if saved->SyncFs.exists {
        target->makeParentDirectory
        SyncFs.rename(saved, target)
      }
    })

    if indexPath->SyncFs.exists {
      SyncFs.remove(indexPath, {force: true})
    }
    let savedIndex = Path.join([backup, "index.json"])
    if savedIndex->SyncFs.exists {
      SyncFs.rename(savedIndex, indexPath)
    }

    if configPath->SyncFs.exists {
      SyncFs.remove(configPath, {force: true})
    }
    if configBackup->SyncFs.exists {
      SyncFs.rename(configBackup, configPath)
    }
    SyncFs.remove(configTemporary, {force: true})
    SyncFs.remove(backup, {recursive: true, force: true})
    SyncFs.remove(stage, {recursive: true, force: true})
    JsExn.throw(error)
  }
}

let runCli = async (t: t<_>, ~args: option<array<string>>=?) => {
  let debugging = ref(false)
  let debug = message =>
    if debugging.contents {
      Console.debug(message)
    }
  let args = args->Option.getOr(argv->Array.slice(~start=2)->Array.keepSome)
  debugging := args->CliArgs.hasArg("--debug")

  switch args[0] {
  | Some("extract") =>
    let filePath = switch args[1] {
    | Some(path) => path
    | None => panic("You must supply a file path as the second argument to extract")
    }
    let content = await Internal.extractContentInFile(
      filePath,
      [FileName.getFullExtension(t.fileName)],
    )
    content->JSON.stringifyAny->Console.log
  | Some("generate") =>
    let config = await t.setup({args: args})
    let watch = args->CliArgs.hasArg("--watch")
    let outputDir = switch args->CliArgs.getArgValue(["--output"]) {
    | None => panic("--output must be set. It controls where generated files are emitted.")
    | Some(output) => Path.resolve([Process.process->Process.cwd, output])
    }
    let src = switch args->CliArgs.getArgValue(["--src"]) {
    | None => panic("--src must be set. It controls where to look for source ReScript files.")
    | Some(src) => Path.resolve([Process.process->Process.cwd, src])
    }
    let configPath = switch args->CliArgs.getArgValue(["--embed-lang-config"]) {
    | Some(path) => Path.resolve([Process.process->Process.cwd, path])
    | None => Path.join([outputDir, "rescript-embed-lang.json"])
    }
    try {
      await Fs.access(outputDir)
    } catch {
    | JsExn(_) => await Fs.mkdirWith(outputDir, {recursive: true})
    }

    let runGenerationNow = async () => {
      let matches = getMatches(~root=src)
      let perSource = await Promise.all(
        matches->Array.map(path => t->proposeForSource(path, ~config, ~outputDir, ~debug)),
      )
      let proposed = perSource->Array.flat
      proposed->validateCollisions
      validateSourceModuleCollisions(proposed, matches)
      let configContent = await prepareConfig(
        ~path=configPath,
        ~extension=FileName.getExtensionName(t.fileName),
        ~generatedName=t.generatedName->GeneratedName.toJson,
      )
      await commitFiles(
        ~outputDir,
        ~extension=FileName.getExtensionName(t.fileName),
        ~files=proposed,
        ~configPath,
        ~configContent,
      )
      Console.log(
        if proposed->Array.length === 0 {
          "No embeds found"
        } else {
          `Generated ${proposed->Array.length->Int.toString} files.`
        },
      )
    }

    let running = ref(false)
    let pending = ref(false)
    let runCoalesced = async (~files=?) => {
      ignore(files)
      pending := true
      if !running.contents {
        running := true
        while pending.contents {
          pending := false
          try {
            await runGenerationNow()
          } catch {
          | JsExn(error) if watch =>
            Console.error(
              `${colorRed("Generation failed")}: ${error
                ->JsExn.message
                ->Option.getOr("unknown error")}`,
            )
          }
        }
        running := false
      }
    }

    await runCoalesced()
    if watch {
      Console.log(`Watching for changes in ${src}...`)
      let _watcher =
        Chokidar.watcher
        ->Chokidar.watch(
          `${src}/**/*.res`,
          ~options={ignored: ["**/node_modules", outputDir], ignoreInitial: true},
        )
        ->Chokidar.Watcher.onChange(async _ => await runCoalesced())
        ->Chokidar.Watcher.onAdd(async _ => await runCoalesced())
        ->Chokidar.Watcher.onUnlink(async _ => await runCoalesced())
      ignore(_watcher)
      switch t.onWatch {
      | None => ()
      | Some(onWatch) => await onWatch({config, runGeneration: runCoalesced, debug})
      }
    }
  | Some(command) =>
    switch t.handleOtherCommand {
    | None => Console.log(t.cliHelpText)
    | Some(handleOtherCommand) =>
      await handleOtherCommand({args, command, config: await t.setup({args: args})})
    }
  | None => Console.log(t.cliHelpText)
  }
}
