module Path = NodeJs.Path
module Process = NodeJs.Process
module Fs = NodeJs.Fs
module CodegenUtils = RescriptEmbedLang__CodegenUtils
module Internal = RescriptEmbedLang__Internal

let colorRed = str => `\x1b[31m${str}\x1b[0m`

module Chokidar = {
  type t
  module Watcher = {
    type t
    @send external onChange: (t, @as(json`"change"`) _, string => promise<unit>) => t = "on"
    @send external onUnlink: (t, @as(json`"unlink"`) _, string => promise<unit>) => t = "on"
    @send external onAdd: (t, @as(json`"add"`) _, string => promise<unit>) => t = "on"
  }
  @module("chokidar") @val external watcher: t = "default"
  @live type watchOptions = {ignored?: array<string>, ignoreInitial?: bool}
  @send external watch: (t, string, ~options: watchOptions=?) => Watcher.t = "watch"
}

module Glob = {
  @live type opts = {dot?: bool, cwd?: string, absolute?: bool}
  @live type glob = {sync: (array<string>, opts) => array<string>}
  @module("fast-glob") external glob: glob = "default"
}

module Hash = {
  type createHash
  @module("node:crypto") external createHash: createHash = "createHash"
  let digest: (
    createHash,
    string,
    string,
  ) => string = %raw(`function(createHash, algorithm, contents) {
    return createHash(algorithm).update(contents, "utf8").digest("hex")
  }`)
  let sha256 = contents => digest(createHash, "sha256", contents)
  let md5 = contents => digest(createHash, "md5", contents)
}

let configVersion = 1
let generatorFormatVersion = 1
let ownershipHeader = "// @generated by rescript-embed-lang v1"
let toFileBaseName = fileName => Path.basenameExt(fileName, ".res")

module Vm = {
  type runInNewContext
  @module("node:vm") external runInNewContext: runInNewContext = "runInNewContext"
}

@live type extensionPattern = Generic(string) | FirstClass(string)
@live type cardinality = ExactlyOne | First
@live type capture = Numbered(int) | Named(string)
@live
type generatedName =
  | Sequential
  | Regex({pattern: string, flags: string, capture: capture, cardinality: cardinality})

module GeneratedName = {
  @live type extraction = {name: string, matchCount: int}

  let describeCapture = capture =>
    switch capture {
    | Numbered(index) => `numbered capture ${index->Int.toString}`
    | Named(name) => `named capture "${name}"`
    }

  let extractRegex: (
    Vm.runInNewContext,
    ~pattern: string,
    ~flags: string,
    ~captureKind: string,
    ~captureValue: string,
    ~cardinality: string,
    ~source: string,
  ) => extraction = %raw(`function(runInNewContext, pattern, flags, captureKind, captureValue, cardinality, source) {
    let regexp;
    try {
      const iterationFlags =
        cardinality === "exactlyOne" && !flags.includes("g") && !flags.includes("y")
          ? flags + "g"
          : flags;
      regexp = new RegExp(pattern, iterationFlags);
    } catch (error) {
      throw new Error("invalid ECMAScript regex /" + pattern + "/" + flags + ": " + error.message);
    }
    regexp.lastIndex = 0;
    const matches = [];
    while (matches.length < (cardinality === "exactlyOne" ? 2 : 1)) {
      let match;
      try {
        match = runInNewContext("regexp.exec(source)", {regexp, source}, {timeout: 100});
      } catch (error) {
        if (error.code === "ERR_SCRIPT_EXECUTION_TIMEOUT") {
          throw new Error("generated-name regex /" + pattern + "/" + flags + " timed out after 100ms");
        }
        throw error;
      }
      if (match === null) break;
      matches.push(match);
      if (!regexp.global && !regexp.sticky) break;
      if (match[0] === "") regexp.lastIndex += 1;
    }
    if (matches.length === 0) {
      throw new Error("generated-name regex /" + pattern + "/" + flags + " did not match");
    }
    if (cardinality === "exactlyOne" && matches.length > 1) {
      throw new Error("generated-name regex /" + pattern + "/" + flags + " matched more than once");
    }
    const match = matches[0];
    const value = captureKind === "numbered"
      ? match[Number(captureValue)]
      : match.groups?.[captureValue];
    if (value === undefined) {
      throw new Error(captureKind + " capture " + captureValue + " was missing for regex /" + pattern + "/" + flags);
    }
    if (value === "") {
      throw new Error(captureKind + " capture " + captureValue + " was empty for regex /" + pattern + "/" + flags);
    }
    if (!/^[_A-Za-z][_0-9A-Za-z]*$/.test(value)) {
      throw new Error('extracted generated name "' + value + '" is invalid; expected [_A-Za-z][_0-9A-Za-z]*');
    }
    return {name: value, matchCount: matches.length};
  }`)

  let extract = (~extension, ~source, config) =>
    switch config {
    | Sequential => None
    | Regex({pattern, flags, capture, cardinality}) =>
      let (captureKind, captureValue) = switch capture {
      | Numbered(index) => ("numbered", index->Int.toString)
      | Named(name) => ("named", name)
      }
      let cardinality = switch cardinality {
      | ExactlyOne => "exactlyOne"
      | First => "first"
      }
      try {
        Some(
          extractRegex(
            Vm.runInNewContext,
            ~pattern,
            ~flags,
            ~captureKind,
            ~captureValue,
            ~cardinality,
            ~source,
          ).name,
        )
      } catch {
      | JsExn(error) =>
        panic(
          `extension "${extension}": ${error
            ->JsExn.message
            ->Option.getOr("name extraction failed")} (${capture->describeCapture})`,
        )
      }
    }

  let sequentialJson: unit => JSON.t = %raw(`function() { return {kind: "sequential"}; }`)
  let regexJson: (
    ~pattern: string,
    ~flags: string,
    ~captureKind: string,
    ~captureValue: string,
    ~cardinality: string,
  ) => JSON.t = %raw(`function(pattern, flags, captureKind, captureValue, cardinality) {
    return {
      kind: "regex",
      pattern,
      flags,
      capture: captureKind === "numbered"
        ? {kind: "numbered", index: Number(captureValue)}
        : {kind: "named", name: captureValue},
      cardinality
    };
  }`)

  let toJson = config =>
    switch config {
    | Sequential => sequentialJson()
    | Regex({pattern, flags, capture, cardinality}) =>
      let (captureKind, captureValue) = switch capture {
      | Numbered(index) => ("numbered", index->Int.toString)
      | Named(name) => ("named", name)
      }
      regexJson(
        ~pattern,
        ~flags,
        ~captureKind,
        ~captureValue,
        ~cardinality=switch cardinality {
        | ExactlyOne => "exactlyOne"
        | First => "first"
        },
      )
    }
}

module FileName = {
  type t = {pattern: extensionPattern}
  let make = (pattern: extensionPattern) => {pattern: pattern}
  let getExtensionName = t =>
    switch t.pattern {
    | Generic(extension) | FirstClass(extension) => extension
    }
  let getFullExtension = t =>
    switch t.pattern {
    | Generic(extension) => `%generated.${extension}`
    | FirstClass(extension) => `%${extension}`
    }
  let toGeneratedFileName = (t, fileName, ~extension="res") =>
    `${toFileBaseName(fileName)}__${t->getExtensionName}.${extension}`
  let toNamedGeneratedFileName = (t, fileName, generatedName, ~extension="res") =>
    `${toFileBaseName(fileName)}__${t->getExtensionName}__${generatedName}.${extension}`
}

module CliArgs = {
  type t = array<string>
  let hasArg = (args, name) => args->Array.includes(name)
  let getArgValue = (args, names) => {
    let index = args->Array.findIndexOpt(item => names->Array.includes(item))
    switch index {
    | Some(index) =>
      switch args[index + 1] {
      | Some(value) if !(value->String.startsWith("--")) => Some(value)
      | _ => None
      }
    | None => None
    }
  }
}

@tag("kind") @live
type generated =
  | WithModuleName({moduleName: string, content: string})
  | NoModuleName({content: string})
@live type emitFileReturn = {path: string, fileName: string}
@live type loc = {line: int, col: int}
@live type fileLocation = {start: loc, end: loc}
@live
type generateConfig<'config> = {
  location: fileLocation,
  path: string,
  config: 'config,
  content: string,
  emitExtraFile: (
    ~extension: string,
    ~content: string,
    ~moduleName: option<string>,
  ) => emitFileReturn,
}
@live
type handleOtherCommandConfig<'config> = {
  command: string,
  args: array<string>,
  config: 'config,
}
@live type setupConfig = {args: CliArgs.t}
@live
type onWatchConfig<'config> = {
  config: 'config,
  runGeneration: (~files: array<string>=?) => promise<unit>,
  debug: string => unit,
}

type t<'config> = {
  fileName: FileName.t,
  generatedName: generatedName,
  setup: setupConfig => promise<'config>,
  generate: generateConfig<'config> => promise<result<generated, string>>,
  cliHelpText: string,
  handleOtherCommand?: handleOtherCommandConfig<'config> => promise<unit>,
  onWatch?: onWatchConfig<'config> => promise<unit>,
}

let defaultSetup = async _ => ()

let make = (
  ~extensionPattern,
  ~generatedName=Sequential,
  ~setup,
  ~generate,
  ~cliHelpText,
  ~handleOtherCommand=?,
  ~onWatch=?,
) => {
  fileName: FileName.make(extensionPattern),
  generatedName,
  setup,
  generate,
  cliHelpText,
  ?handleOtherCommand,
  ?onWatch,
}

let getMatches = (~root) => Glob.glob.sync(["**/*.res"], {cwd: root, absolute: true})
@val external argv: array<option<string>> = "process.argv"

@live
type proposedFile = {
  fileName: string,
  content: string,
  sourcePath: string,
  line: int,
  col: int,
}

let sourceHash = (~extension, ~source) =>
  Hash.sha256(
    "rescript-embed-lang\x00format=" ++
    generatorFormatVersion->Int.toString ++
    "\x00config=" ++
    configVersion->Int.toString ++
    "\x00extension=" ++
    extension ++
    "\x00source=" ++
    source,
  )

let indent = content => content->String.split("\n")->Array.join("\n  ")
let diagnostic = (~path, ~location: fileLocation, ~extension, message) =>
  `${path}:${(location.start.line + 1)->Int.toString}:${(location.start.col + 1)
      ->Int.toString} [${extension}] ${message}`

let proposeForSource = async (t: t<_>, path, ~config, ~outputDir, ~debug) => {
  let extension = FileName.getExtensionName(t.fileName)
  let fullExtension = FileName.getFullExtension(t.fileName)
  let embeds =
    (await path->Internal.findContentInFile([fullExtension]))->Array.filter(embed =>
      "%" ++ embed.extensionName === fullExtension
    )

  switch t.generatedName {
  | Sequential if embeds->Array.length === 0 => []
  | Sequential =>
    let modulesAndExtras = await Promise.all(
      embeds->Array.mapWithIndex(async (embed, index) => {
        let extraFiles: array<proposedFile> = []
        let location = {
          start: {line: embed.loc["start"]["line"], col: embed.loc["start"]["character"]},
          end: {line: embed.loc["end"]["line"], col: embed.loc["end"]["character"]},
        }
        let result = try {
          await t.generate({
            path,
            location,
            config,
            content: embed.contents,
            emitExtraFile: (~extension as extraExtension, ~content, ~moduleName) => {
              debug(`[emit] Emitting extra file with extension .${extraExtension}`)
              let moduleName = moduleName->Option.getOr(`M${(index + 1)->Int.toString}`)
              let fileName = `${toFileBaseName(path)}__${extension}.${moduleName}.${extraExtension}`
              extraFiles->Array.push({
                fileName,
                content,
                sourcePath: path,
                line: location.start.line,
                col: location.start.col,
              })
              {path: Path.resolve([outputDir, fileName]), fileName}
            },
          })
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("generator failed"),
            ),
          )
        }
        switch result {
        | Error(message) => panic(diagnostic(~path, ~location, ~extension, message))
        | Ok(WithModuleName({moduleName, content})) => (moduleName, content, extraFiles)
        | Ok(NoModuleName({content})) => (`M${(index + 1)->Int.toString}`, content, extraFiles)
        }
      }),
    )
    let generatedContent =
      modulesAndExtras
      ->Array.map(((moduleName, content, _)) => `module ${moduleName} = {\n  ${content->indent}\n}`)
      ->Array.join("\n\n")
    let fileName = t.fileName->FileName.toGeneratedFileName(path)
    let generated = {
      fileName,
      content: `${ownershipHeader}\n// @sourceHash ${generatedContent->Hash.md5}\n\n${generatedContent}`,
      sourcePath: path,
      line: 0,
      col: 0,
    }
    [generated, ...modulesAndExtras->Array.flatMap(((_, _, extras)) => extras)]
  | Regex(_) =>
    let proposed = await Promise.all(
      embeds->Array.map(async embed => {
        let location = {
          start: {line: embed.loc["start"]["line"], col: embed.loc["start"]["character"]},
          end: {line: embed.loc["end"]["line"], col: embed.loc["end"]["character"]},
        }
        let generatedName = try {
          t.generatedName
          ->GeneratedName.extract(~extension, ~source=embed.contents)
          ->Option.getOrThrow
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("name extraction failed"),
            ),
          )
        }
        let extraFiles: array<proposedFile> = []
        let result = try {
          await t.generate({
            path,
            location,
            config,
            content: embed.contents,
            emitExtraFile: (~extension as extraExtension, ~content, ~moduleName) => {
              let artifactName = moduleName->Option.getOr(generatedName)
              let fileName = `${toFileBaseName(
                  path,
                )}__${extension}__${artifactName}.${extraExtension}`
              extraFiles->Array.push({
                fileName,
                content,
                sourcePath: path,
                line: location.start.line,
                col: location.start.col,
              })
              {path: Path.resolve([outputDir, fileName]), fileName}
            },
          })
        } catch {
        | JsExn(error) =>
          panic(
            diagnostic(
              ~path,
              ~location,
              ~extension,
              error->JsExn.message->Option.getOr("generator failed"),
            ),
          )
        }
        let generatedContent = switch result {
        | Error(message) => panic(diagnostic(~path, ~location, ~extension, message))
        | Ok(WithModuleName({content})) | Ok(NoModuleName({content})) => content
        }
        let hash = sourceHash(~extension, ~source=embed.contents)
        let fileName = t.fileName->FileName.toNamedGeneratedFileName(path, generatedName)
        [
          {
            fileName,
            content: `${ownershipHeader}\nmodule SourceHash_${hash} = {\n  ${generatedContent->indent}\n}\n`,
            sourcePath: path,
            line: location.start.line,
            col: location.start.col,
          },
          ...extraFiles,
        ]
      }),
    )
    proposed->Array.flat
  }
}

let validateCollisions: array<proposedFile> => unit = %raw(`function(files) {
  const seen = new Map();
  for (const file of files) {
    const key = file.fileName.toLocaleLowerCase("en-US");
    const previous = seen.get(key);
    if (previous !== undefined) {
      throw new Error(
        file.sourcePath + ":" + (file.line + 1) + ":" + (file.col + 1) +
        " generated output collision for " + JSON.stringify(file.fileName) +
        "; first proposed at " + previous.sourcePath + ":" +
        (previous.line + 1) + ":" + (previous.col + 1)
      );
    }
    seen.set(key, file);
  }
}`)

let validateSourceModuleCollisions = (files: array<proposedFile>, sourceFiles: array<string>) => {
  let userModules = sourceFiles->Array.filterMap(path => {
    let content = try {
      path->Fs.readFileSync->NodeJs.Buffer.toString
    } catch {
    | JsExn(_) => ""
    }
    if content->String.startsWith(ownershipHeader) {
      None
    } else {
      Some((Path.basename(path)->String.toLowerCase, path))
    }
  })

  files->Array.forEach(file => {
    if file.fileName->String.endsWith(".res") {
      let key = file.fileName->String.toLowerCase
      switch userModules->Array.find(((moduleName, _)) => moduleName === key) {
      | None => ()
      | Some((_, userPath)) =>
        panic(
          `${file.sourcePath}:${(file.line + 1)->Int.toString}:${(file.col + 1)
              ->Int.toString} generated module "${file.fileName}" collides with user module "${userPath}"`,
        )
      }
    }
  })
}

let prepareConfig: (
  ~path: string,
  ~extension: string,
  ~generatedName: JSON.t,
) => promise<string> = %raw(`async function(path, extension, generatedName) {
  const fs = await import("node:fs");
  let config = {version: 1, extensions: {}};
  if (fs.existsSync(path)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(path, "utf8"));
      if (parsed.version !== 1) {
        throw new Error("unsupported existing config version " + parsed.version);
      }
      config = parsed;
    } catch (error) {
      throw new Error(
        "cannot update embed-language config " + JSON.stringify(path) + ": " + error.message
      );
    }
  }
  config.extensions[extension] = {generatedName};
  return JSON.stringify(config, null, 2) + "\n";
}`)

let commitFiles: (
  ~outputDir: string,
  ~extension: string,
  ~files: array<proposedFile>,
  ~configPath: string,
  ~configContent: string,
) => promise<unit> = %raw(`async function(
  outputDir,
  extension,
  files,
  configPath,
  configContent
) {
  const fs = await import("node:fs");
  const path = await import("node:path");
  const indexPath = path.join(outputDir, ".rescript-embed-lang-" + extension + ".json");
  let previous = [];
  if (fs.existsSync(indexPath)) {
    try {
      const index = JSON.parse(fs.readFileSync(indexPath, "utf8"));
      if (index.version === 1 && Array.isArray(index.files)) previous = index.files;
    } catch (error) {
      throw new Error(
        "cannot read ownership index " + JSON.stringify(indexPath) + ": " + error.message
      );
    }
  }

  const directoryEntries = fs.readdirSync(outputDir);
  for (const fileName of directoryEntries) {
    if (!fileName.endsWith("__" + extension + ".res")) continue;
    const candidate = path.join(outputDir, fileName);
    if (!fs.statSync(candidate).isFile()) continue;
    const content = fs.readFileSync(candidate, "utf8");
    if (!content.startsWith("// @sourceHash ")) continue;
    previous.push(fileName);
    const prefix = fileName.slice(0, -4);
    for (const extraName of directoryEntries) {
      if (extraName.startsWith(prefix + ".")) previous.push(extraName);
    }
  }
  previous = [...new Set(previous)];

  const previousSet = new Set(previous);
  const existingByFold = new Map(
    fs.readdirSync(outputDir).map(fileName => [
      fileName.toLocaleLowerCase("en-US"),
      fileName
    ])
  );
  for (const file of files) {
    const caseExisting = existingByFold.get(file.fileName.toLocaleLowerCase("en-US"));
    const existingName = caseExisting === undefined ? file.fileName : caseExisting;
    const target = path.join(outputDir, existingName);
    if (fs.existsSync(target) && !previousSet.has(existingName)) {
      const content = fs.readFileSync(target, "utf8");
      if (!content.startsWith("// @generated by rescript-embed-lang v1")) {
        throw new Error(
          file.sourcePath + ":" + (file.line + 1) + ":" + (file.col + 1) +
          " generated file " + JSON.stringify(file.fileName) +
          " collides with user-owned file " + JSON.stringify(existingName)
        );
      }
    }
  }

  const stage = fs.mkdtempSync(path.join(outputDir, ".rescript-embed-lang-stage-"));
  const backup = fs.mkdtempSync(path.join(outputDir, ".rescript-embed-lang-backup-"));
  const transactionId = process.pid + "-" + Date.now();
  const configTemporary = configPath + ".tmp-" + transactionId;
  const configBackup = configPath + ".backup-" + transactionId;
  const affected = new Set([...previous, ...files.map(file => file.fileName)]);

  try {
    for (const file of files) {
      const staged = path.join(stage, file.fileName);
      fs.mkdirSync(path.dirname(staged), {recursive: true});
      fs.writeFileSync(staged, file.content);
    }
    fs.writeFileSync(
      path.join(stage, "index.json"),
      JSON.stringify({
        version: 1,
        extension,
        files: files.map(file => file.fileName)
      }, null, 2) + "\n"
    );
    fs.mkdirSync(path.dirname(configPath), {recursive: true});
    fs.writeFileSync(configTemporary, configContent);

    for (const fileName of affected) {
      const target = path.join(outputDir, fileName);
      if (fs.existsSync(target)) {
        const saved = path.join(backup, fileName);
        fs.mkdirSync(path.dirname(saved), {recursive: true});
        fs.renameSync(target, saved);
      }
    }
    if (fs.existsSync(indexPath)) {
      fs.renameSync(indexPath, path.join(backup, "index.json"));
    }
    if (fs.existsSync(configPath)) fs.renameSync(configPath, configBackup);

    for (const file of files) {
      const target = path.join(outputDir, file.fileName);
      fs.mkdirSync(path.dirname(target), {recursive: true});
      fs.renameSync(path.join(stage, file.fileName), target);
    }
    fs.renameSync(path.join(stage, "index.json"), indexPath);
    fs.renameSync(configTemporary, configPath);

    fs.rmSync(configBackup, {force: true});
    fs.rmSync(backup, {recursive: true, force: true});
    fs.rmSync(stage, {recursive: true, force: true});
  } catch (error) {
    for (const fileName of affected) {
      const target = path.join(outputDir, fileName);
      if (fs.existsSync(target)) fs.rmSync(target, {force: true});
      const saved = path.join(backup, fileName);
      if (fs.existsSync(saved)) {
        fs.mkdirSync(path.dirname(target), {recursive: true});
        fs.renameSync(saved, target);
      }
    }

    if (fs.existsSync(indexPath)) fs.rmSync(indexPath, {force: true});
    const savedIndex = path.join(backup, "index.json");
    if (fs.existsSync(savedIndex)) fs.renameSync(savedIndex, indexPath);

    if (fs.existsSync(configPath)) fs.rmSync(configPath, {force: true});
    if (fs.existsSync(configBackup)) fs.renameSync(configBackup, configPath);
    fs.rmSync(configTemporary, {force: true});
    fs.rmSync(backup, {recursive: true, force: true});
    fs.rmSync(stage, {recursive: true, force: true});
    throw error;
  }
}`)

let runCli = async (t: t<_>, ~args: option<array<string>>=?) => {
  let debugging = ref(false)
  let debug = message =>
    if debugging.contents {
      Console.debug(message)
    }
  let args = args->Option.getOr(argv->Array.slice(~start=2)->Array.keepSome)
  debugging := args->CliArgs.hasArg("--debug")

  switch args[0] {
  | Some("extract") =>
    let filePath = switch args[1] {
    | Some(path) => path
    | None => panic("You must supply a file path as the second argument to extract")
    }
    let content = await Internal.extractContentInFile(
      filePath,
      [FileName.getFullExtension(t.fileName)],
    )
    content->JSON.stringifyAny->Console.log
  | Some("generate") =>
    let config = await t.setup({args: args})
    let watch = args->CliArgs.hasArg("--watch")
    let outputDir = switch args->CliArgs.getArgValue(["--output"]) {
    | None => panic("--output must be set. It controls where generated files are emitted.")
    | Some(output) => Path.resolve([Process.process->Process.cwd, output])
    }
    let src = switch args->CliArgs.getArgValue(["--src"]) {
    | None => panic("--src must be set. It controls where to look for source ReScript files.")
    | Some(src) => Path.resolve([Process.process->Process.cwd, src])
    }
    let configPath = switch args->CliArgs.getArgValue(["--embed-lang-config"]) {
    | Some(path) => Path.resolve([Process.process->Process.cwd, path])
    | None => Path.join([outputDir, "rescript-embed-lang.json"])
    }
    try {
      await Fs.access(outputDir)
    } catch {
    | JsExn(_) => await Fs.mkdirWith(outputDir, {recursive: true})
    }

    let runGenerationNow = async () => {
      let matches = getMatches(~root=src)
      let perSource = await Promise.all(
        matches->Array.map(path => t->proposeForSource(path, ~config, ~outputDir, ~debug)),
      )
      let proposed = perSource->Array.flat
      proposed->validateCollisions
      validateSourceModuleCollisions(proposed, matches)
      let configContent = await prepareConfig(
        ~path=configPath,
        ~extension=FileName.getExtensionName(t.fileName),
        ~generatedName=t.generatedName->GeneratedName.toJson,
      )
      await commitFiles(
        ~outputDir,
        ~extension=FileName.getExtensionName(t.fileName),
        ~files=proposed,
        ~configPath,
        ~configContent,
      )
      Console.log(
        if proposed->Array.length === 0 {
          "No embeds found"
        } else {
          `Generated ${proposed->Array.length->Int.toString} files.`
        },
      )
    }

    let running = ref(false)
    let pending = ref(false)
    let runCoalesced = async (~files=?) => {
      ignore(files)
      pending := true
      if !running.contents {
        running := true
        while pending.contents {
          pending := false
          try {
            await runGenerationNow()
          } catch {
          | JsExn(error) if watch =>
            Console.error(
              `${colorRed("Generation failed")}: ${error
                ->JsExn.message
                ->Option.getOr("unknown error")}`,
            )
          }
        }
        running := false
      }
    }

    await runCoalesced()
    if watch {
      Console.log(`Watching for changes in ${src}...`)
      let _watcher =
        Chokidar.watcher
        ->Chokidar.watch(
          `${src}/**/*.res`,
          ~options={ignored: ["**/node_modules", outputDir], ignoreInitial: true},
        )
        ->Chokidar.Watcher.onChange(async _ => await runCoalesced())
        ->Chokidar.Watcher.onAdd(async _ => await runCoalesced())
        ->Chokidar.Watcher.onUnlink(async _ => await runCoalesced())
      ignore(_watcher)
      switch t.onWatch {
      | None => ()
      | Some(onWatch) => await onWatch({config, runGeneration: runCoalesced, debug})
      }
    }
  | Some(command) =>
    switch t.handleOtherCommand {
    | None => Console.log(t.cliHelpText)
    | Some(handleOtherCommand) =>
      await handleOtherCommand({args, command, config: await t.setup({args: args})})
    }
  | None => Console.log(t.cliHelpText)
  }
}
